layout_spectrum: 0.20365229545502306
typography_spectrum: 0.9818304599619627
color:
  brandStrength: 0.5607049033307646
  lightness: 0.5862714339681153
  saturation: 0.48495416376656747
  rhythmicContrast: 0.7679964482211646
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
name: mediaspajz.info
navigation:
  - name: 'keresés '
    url: 'http://mediaspajz.info'
    type: external
title: Médiaspájz
content: []
description: a hírek már a spájzban vannak…
purpose:
  - type: contact
    url: 'mailto:hello@mediaspajz.info'
    label: írj nekünk
