layout_spectrum: 0.7369512641818106
typography_spectrum: 0.554363143931853
color:
  brandStrength: 0.4954701573980769
  lightness: 0.2520180091280306
  saturation: 0.8372669027474625
  rhythmicContrast: 0.3097516441169093
  brandColors:
    - '#1C67AA'
    - '#FFFFFF'
    - '#B4D2E6'
    - '#364860'
    - '#88B4D9'
github: true
name: mediaspajz.info
navigation:
  - name: 'keresés '
    url: 'http://mediaspajz.info'
    type: external
title: Médiaspájz
content: []
description: a hírek már a spájzban vannak…
purpose:
  - type: contact
    url: 'mailto:hello@mediaspajz.info'
    label: írj nekünk
